### ISSUE TITLE
Data exports outputs need parameterized prefixes

### ISSUE THREAD

**Issue by cygnus8595** [aws-solutions-library-samples/cloud-intelligence-dashboards-data-collection#282]
The output names for resources in the [data exports aggregation template](https://github.com/awslabs/cid-data-collection-framework/blob/main/data-exports/deploy/data-exports-aggregation.yaml#L1513) don't have parameterized prefixes, so running the same stack multiple times will fail because they're creating the same outputs.

Example:
```
AggregateBucketName:
    Description: Bucket with aggregate Data Exports
    Value: !Sub ${ResourcePrefix}-${DestinationAccountId}-data-exports
    Export: { Name:  'cid-DataExports-Bucket'}
```
Could be:
```
AggregateBucketName:
    Description: Bucket with aggregate Data Exports
    Value: !Sub ${ResourcePrefix}-${DestinationAccountId}-data-exports
    Export:
        Name: !Sub "${ResourcePrefix}-DataExports-Bucket"
```
This would allow multiple stacks in the same account.
